# Generated by Django 4.1.1 on 2022-10-11 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('description', models.CharField(default='Description', help_text='Category description', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Item name', max_length=255)),
                ('description', models.CharField(default='Description', help_text='Item description', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(default='Description', help_text='Description', max_length=255)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
