# Generated by Django 4.1.1 on 2022-10-06 14:00

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95786))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95799))),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('description', models.CharField(default='Description', help_text='Category description', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95786))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95799))),
                ('description', models.CharField(default='Description', help_text='Description', max_length=255)),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(default='Code', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95786)),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='Description', help_text='Item description', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Images'),
        ),
        migrations.AddField(
            model_name='item',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95799)),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95786))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95799))),
                ('description', models.CharField(default='Description', help_text='Description', max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID', primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95786))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 14, 0, 3, 95799))),
                ('description', models.CharField(default='Description', help_text='Description', max_length=255)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(to='items.product')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='items.category'),
            preserve_default=False,
        ),
    ]
